[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
[[plugins]]
  package = "netlify-plugin-cypress"
  [plugins.inputs.postBuild]
    enable = true

  [plugins.inputs]
    enable = false
    
  [[redirects]]
  from = "/"
  to = "https://afflat3e1.com/lnk.asp?o=9851&c=918277&a=403969&k=11F3738D39B3DB2BE2C6EEBB46EC312D&l=9540"
  status = 301
  force = true
